2024-12-08 08:57:21,959 - ERROR - Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "/var/www/urban/module12/tests_12_4.py", line 21, in test_run
    runner1 = Runner(50)
              ^^^^^^^^^^
  File "/var/www/urban/module12/rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-12-08 08:57:21,960 - ERROR - Неверная скорость для Runner
